create page to rate
OUMAREGA/IPSSIProjectFront pull request #7
Opened 2020-02-01 19:47 UTC by OUMAREGA

# Description

Décrire vos changements apportés ainsi que le problème en question qui a été résolu.
Page pour noter une fonctionnalité
**Cocher les mentions utiles**

- [ ] Correction d'un bug
- [ ] Nouvelle fonctionnalité
- [ ] Changements critiques

**Décrire les tests qui ont été effectués**

Configuration de test
* Système d'exploitation :
* Version utilisée :

2020-02-01 20:00 UTC, ii02735 requested changes

2020-02-01 20:00 UTC, ii02735 commented on rate.html
> +                <h2>Noter le module {{module}} pour l'interveant {{interveant}}</h2>
Quel template devra être utilisé ici ?

2020-02-01 20:00 UTC, ii02735 commented on rate.html
> +                    <p>Votre note devra tenir compte des critéres suivants:</p>
Votre note devra tenir compte des **critères** suivants :

2020-02-01 20:00 UTC, ii02735 commented on rate.html
> +                        <li><span class="badge badge-info">Compréhension du cours</span></li>
Application du **style** inutile ici (alourdissant)

2020-02-01 20:00 UTC, ii02735 commented on rate.html
> +                    <input type="text" class="custom-select my-1 mr-sm-1" id="inlineFormCustom" placeholder="Note/20" >
L'utilisateur devra t-il entrer une note au format <note>/20 ou directement le nombre ? 
Il ne faudra pas oublier que **cette valeur sera ensuite interprétée** en JS par le biais de l'API.

2020-02-01 21:44 UTC, OUMAREGA commented on rate.html
> +                <h2>Noter le module {{module}} pour l'interveant {{interveant}}</h2>
L'étudiant aura sur une page la liste de ses modules, sur click ça redirige sur rate.html
on aura accés au nom du module et de l'intervenant qui correspondent à {{module}} et {{interveant}}

2020-02-01 21:46 UTC, OUMAREGA commented on rate.html
> +                        <li><span class="badge badge-info">Compréhension du cours</span></li>
j'ai pas envi d'avoir des puces avec texte simple avec le fond blanc de la page, c'est basique et vilain, donc j'ai besoin du style

2020-02-01 21:48 UTC, OUMAREGA commented on rate.html
> +                    <input type="text" class="custom-select my-1 mr-sm-1" id="inlineFormCustom" placeholder="Note/20" >
il est censé renseigner une note exemple 18. Évidemment c'est à nous de verifier ce qu'il entre si c'est un nombre, si c'est >= 0 etc

2020-02-01 22:04 UTC, OUMAREGA commented on rate.html
> +                    <p>Votre note devra tenir compte des critéres suivants:</p>
d'accord

2020-02-01 22:11 UTC, OumarCh commented on rate.html
> +                    <p>Votre note devra tenir compte des critéres suivants:</p>
Enlèves l'onglet sessions du menu

2020-02-01 22:18 UTC, OUMAREGA commented on rate.html
> +                    <p>Votre note devra tenir compte des critéres suivants:</p>
ça marche

2020-02-01 22:20 UTC, OumarCh commented on rate.html
> +                  <a class="nav-link" href="page-sessions.html" id="Sessions">Sessions <span class="sr-only">(current)</span></a>
Supprimer l'onglet "Sessions" parce que l'internaute est un étudiant.

2020-02-01 22:20 UTC, OumarCh commented on rate.html
> +                  <a class="nav-link" href="page-sessions.html" id="Sessions">Sessions <span class="sr-only">(current)</span></a>
Pour accéder à la liste de ses modules (page d'accueil), il doit cliquer sur IPSSI.

2020-02-01 22:23 UTC, OUMAREGA commented on rate.html
> +                  <a class="nav-link" href="page-sessions.html" id="Sessions">Sessions <span class="sr-only">(current)</span></a>
oui oui si je supprime session je supprime aussi le lien correspondant

2020-02-01 22:42 UTC, ii02735 commented on rate.html
> +                        <li><span class="badge badge-info">Compréhension du cours</span></li>
Bon d'accord

2020-02-01 22:44 UTC, ii02735 commented on rate.html
> +                <h2>Noter le module {{module}} pour l'interveant {{interveant}}</h2>
Ok pour ça, mais comment ces valeurs seront-elles générées ?

2020-02-01 22:51 UTC, ii02735 commented on rate.html
> +                    <input type="text" class="custom-select my-1 mr-sm-1" id="inlineFormCustom" placeholder="Note/20" >
D'accord, c'était juste le placeholder qui m'avait un peu embrouillé

2020-02-02 11:54 UTC, OUMAREGA commented on rate.html
> +                <h2>Noter le module {{module}} pour l'interveant {{interveant}}</h2>
sur la page liste des modules, lors de la redirection vers rate.html il faut y inclure l'id du module cliqué que je récupére et faire des traitements la dessus. Plus facile encore apres click sur la liste des modules on fait apparaitre un drawer et faire les traitements, je vais voir @

2020-02-04 21:06 UTC, OumarCh commented on rate.html
> +                  <a class="nav-link" href="page-sessions.html" id="Sessions">Sessions <span class="sr-only">(current)</span></a>
Juste si c'est un étudiant on affiche pas sessions.

2020-02-05 16:19 UTC, merged